"""Add assignment fields to Asset

Revision ID: 2aef4cb93645
Revises: 1b97b7eeff49
Create Date: 2025-12-11 02:41:39.121156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aef4cb93645'
down_revision = '1b97b7eeff49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('assigned_department', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('assigned_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('assigned_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('assigned_email')
        batch_op.drop_column('assigned_department')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
