"""Add code to Category

Revision ID: caab36e76fa0
Revises: d9b36d125f1b
Create Date: 2025-12-13 15:06:45.044095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caab36e76fa0'
down_revision = 'd9b36d125f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_categories_code', ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_categories_code', type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
