"""Add performed_by to AssetEvent

Revision ID: d9b36d125f1b
Revises: 7507e6085b3c
Create Date: 2025-12-13 03:39:32.787391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b36d125f1b'
down_revision = '7507e6085b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_asset_events_performed_by_id_users",
            "users",
            ["performed_by_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('performed_by_id')

    # ### end Alembic commands ###
